### ISSUE TITLE
getting issue when i've reach at cart page in magento 2

### ISSUE THREAD

**Issue by mukeshsharma1983** [kaviarasankk/Magekmf#1]
Fatal error: Uncaught Error: Class 'Magekmf\Ccavenue\Model\Ccavenue' not found in /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93 Stack trace: #0 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magekmf\\Ccavenu...', Array) #1 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(130): Magento\Framework\ObjectManager\Factory\Compiled->create('Magekmf\\Ccavenu...') #2 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(67): Magento\Framework\ObjectManager\Factory\Compiled->get('Magekmf\\Ccavenu...') #3 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(130): Magento\Framework\ObjectManager\Factory\Compiled->create('Magekmf\\Ccavenu...') #4 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(105): Magento\Framework\ObjectManager\Factory\Compiled->get('Magekmf\\Ccavenu...') #5 /var/www/html/vendor/magento in /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93

**Comment by kaviarasankk** [comment]
Please run `setup:di:compile` command
